[build]
builder = "nixpacks"
buildCommand = "npm install && npx prisma generate && npm run build"

[deploy]
startCommand = "npx prisma db push && node node_modules/next/dist/bin/next start"
restartPolicyType = "on_failure"
